### ISSUE TITLE
Improve alignment of RichText fields

### ISSUE THREAD

**Issue by mikezimm** [mikezimm/drilldown7#346]
## Proposed solution
Just add the transform function below to the same element where I fix the height.
Not sure if it would apply to all rich text or just this one.  Could not find a specific css like 'padding-top' that I could adjust so using transform may be alternative.

```css
element.style {
    max-height: 600em;
    transform: translate(0, -1em);
}
```

![image](https://github.com/mikezimm/drilldown7/assets/49648086/30a21b79-41f3-415c-8404-67e9af6ca612)

**Comment by mikezimm** [comment]
Tested this change in clicky but it ended up pushing the top of a newly created rich text field out of the box.

Maybe see if there is a targeted class for this particular case.

**Comment by mikezimm** [comment]
## Sometimes the transform could push up when you do not want it.
Tested this instead which should only target the first element of the actual rich text the user can modifiy.

``` css
/* https://github.com/mikezimm/drilldown7/issues/346 */
.list-view-rt div:first-of-type *:first-of-type {
  margin-block-start: auto;
}
```
